version: '3'
services:
  datajoint:
    build: .
    environment:
      - DJ_HOST=db
      - DJ_USER=root
      - DJ_PASS=simple
    volumes:
      - ./notebooks:/notebooks
      - ./images:/images
      - .:/src/ibl-pipeline
      - ./data:/data
    links:
      - db
    ports:
      - "8888:8888"
  db:
    image: datajoint/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=simple
    ports:
      - "4306:3306"
  datajoint-ingest:
    build: .
    working_dir: /src/ibl-pipeline
    entrypoint: ibl-shell.py
    command: ingest
    environment:
      - DJ_HOST=db
      - DJ_USER=root
      - DJ_PASS=simple
    volumes:
      - .:/src/ibl-pipeline
      - ./data:/data
    links:
      - db
