version: '3'
services:
  datajoint:
    build: .
    env_file: .env
    volumes:
      - ./notebooks:/notebooks
      - ./images:/images
      - .:/src/IBL-pipeline
      - ./data:/data
      - ./root/.one_params:/root/.one_params
      - ./snapshots:/Figures_DataJoint_shortcuts
    ports:
      - "8888:8888"
  datajoint-ingest:
    build: .
    env_file: .env
    entrypoint: ibl-shell.py
    working_dir: /src/ibl-pipeline
    command: ingest
    volumes:
      - .:/src/ibl-pipeline
      - ./data:/data
