# Setup containers for IBL datajoint pipeline ingestion routines
# Joseph Burling <joseph@datajoint.com>
# --------------------------------------------------------------------------------------
# Basic usage:
#   docker-compose up --detach
#   docker-compose down
#   docker-compose down --volumes

# Shared properties across services ----------------------------------------------------

version: "2.4"

x-img-env-vars: &img-env-vars
  ALYX_LOGIN: ${ALYX_LOGIN:-}
  ALYX_PORT: ${ALYX_PORT:-8000}
  ALYX_PWD: ${ALYX_PWD:-}
  ALYX_URL: ${ALYX_URL:-}
  DJ_HOST: ${DJ_HOST:-datajoint.internationalbrainlab.org}
  DJ_MODE: ${DJ_MODE:-test}
  DJ_PASS: ${DJ_PASS:-}
  DJ_USER: ${DJ_USER:-}
  HTTP_DATA_SERVER_LOGIN: ${HTTP_DATA_SERVER_LOGIN:?set HTTP_DATA_SERVER_LOGIN in .env file}
  HTTP_DATA_SERVER_PWD: ${HTTP_DATA_SERVER_PWD:?set HTTP_DATA_SERVER_PWD in .env file}
  PGDATABASE: ${ALYX_DB_NAME:-alyxdb}
  PGHOST: ${PGHOST:-pgserver}
  PGPASSWORD: ${ALYX_DB_PASSWORD:?set ALYX_DB_PASSWORD in .env file}
  PGUSER: ${ALYX_DB_USER:-alyxadmin}
  S3_ACCESS: ${S3_ACCESS:-}
  S3_MIGRATE_BUCKET: ${S3_MIGRATE_BUCKET:-ibl-dj-external}
  S3_ROOT_PATH: ${S3_ROOT_PATH:-}
  S3_SECRET: ${S3_SECRET:-}

x-ibl-data-volume: &ibl-data-volume
  - type: volume
    source: datacache
    target: /int-brain-lab/data

x-ibl-shared-mount: &ibl-shared-mount
  - type: bind
    source: ../../shared
    target: /int-brain-lab/shared

x-ibl-pipeline-mount: &ibl-pipeline-mount
  - type: bind
    source: ../../ibl_pipeline
    target: /int-brain-lab/IBL-pipeline/ibl_pipeline

x-shared-networks: &shared-networks
  networks:
    ingestion:

x-iblenv-image-common: &iblenv-image-common
  image: iamamutt/iblenv_alyx:latest
  environment:
    <<: *img-env-vars
  init: true
  <<: *shared-networks

x-dj-pipeline-common: &dj-pipeline-common
  <<: *iblenv-image-common
  entrypoint:
    - ingest
  depends_on:
    alyx:
      condition: service_healthy
  volumes:
    - <<: *ibl-data-volume
    - <<: *ibl-shared-mount
    - <<: *ibl-pipeline-mount

services:
  # Postgres Server --------------------------------------------------------------------
  pgserver:
    container_name: postgres_db_server
    environment:
      POSTGRES_DB: ${ALYX_DB_NAME:-alyxdb}
      POSTGRES_PASSWORD: ${ALYX_DB_PASSWORD:?set ALYX_DB_PASSWORD in .env file}
      POSTGRES_USER: ${ALYX_DB_USER:-alyxadmin}
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready
      timeout: 15s
      interval: 1m0s
      retries: 3
      start_period: 30s
    image: postgres:13-bullseye
    <<: *shared-networks
    ports:
      - "5438:5432"
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
        volume: {}

  # IBL Environment for DataJoint Ingestion --------------------------------------------
  alyx:
    <<: *iblenv-image-common
    entrypoint:
      - alyx
    command:
      - wwwpublic
    container_name: alyx_db_server
    depends_on:
      pgserver:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - alyx
        - checkserver
      timeout: 15s
      interval: 30s
      retries: 5
      start_period: 2m0s
    ports:
      - ${ALYX_PORT:-8000}:${ALYX_PORT:-8000}
    volumes:
      - <<: *ibl-data-volume
      - <<: *ibl-shared-mount

  ingest:
    <<: *dj-pipeline-common
    command:
      - config_init
      - --alyxhost=private
      - populate
      - ingest
      - --duration=1
      - --backtrack=3
    scale: ${WORKER_COUNT:-1}

  populate_behavior:
    <<: *dj-pipeline-common
    command:
      - config_init
      - --alyxhost=private
      - populate
      - behavior
      - --duration=1
      - --sleep=10
      - --backtrack=10
    container_name: populate_behavior

  jupyter:
    <<: *dj-pipeline-common
    command:
      - config_init
      - jupyterlab
    container_name: jupyter
    ports:
      - ${JUPYTER_PORT:-10000}:${JUPYTER_PORT:-10000}

# Global Networks and Volumes ----------------------------------------------------------
<<: *shared-networks
volumes:
  datacache:
  pgdata:
