# Setup only postgres and alyx services for dumping json
# Joseph Burling <joseph@datajoint.com>
# --------------------------------------------------------------------------------------
# Basic usage:
#   docker-compose -f docker-compose.yml -f docker-compose-json-dump.yml up -d
#   docker-compose -f docker-compose.yml -f docker-compose-json-dump.yml down --volumes --remove-orphans
#   docker compose -f docker-compose.yml -f docker-compose-json-dump.yml config
#
# alyx --dump_file=/int-brain-lab/shared/public_alyx.sql.gz init_db load_db
# alyx --dump_file=/int-brain-lab/shared/2022-01-12_alyxfull.sql.gz fetch_and_reload_db

version: "3.9"

x-ibl-docker-image: &ibl-docker-image
  image: ${DEV_CONTAINER_IMAGE:-ghcr.io/iamamutt/iblenv_alyx:latest}

services:
  alyx:
    <<: *ibl-docker-image
    command:
      - fetch_and_load_db
      - dump_json
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 2s
    volumes:
      - vscode-server:/home/ibl/.vscode-server/extensions

  iblenv:
    <<: *ibl-docker-image
    deploy:
      mode: replicated
      replicas: 0

  ingest:
    <<: *ibl-docker-image
    deploy:
      mode: replicated
      replicas: 0

  populate_behavior:
    <<: *ibl-docker-image
    deploy:
      mode: replicated
      replicas: 0
