# Debian-based conda environment
# Usage:
#   cd ./docker/conda_base_debian
#   docker-compose up --detach
#   LNX_ARCH=aarch64 docker-compose up --detach
#
#
# Joseph Burling joseph@datajoint.com

services:
  pyenv:
    image: conda_base_debian_pyenv
    platform: linux/${LNX_ARCH:-x86_64}
    init: true
    build:
      context: .
      args:
        GROUPNAME: anaconda
        USERNAME: ${USER:-anaconda}
        USER_GID: ${GID:-1000}
        USER_UID: ${UID:-1000}
    command: [ "python", "--version" ]
