# cd docker/ibl/alyx
# docker-compose up --build --detach pgserv adminer alyx
# ctid="`docker ps -a -q -f name=alyx_alyx`" && docker exec -d $ctid /entrypoint initdb
version: "2.4"

x-common-platform: &common-platform
  platform: linux/${LNX_ARCH:-x86_64}

x-ibl-data-volume: &ibl-data-volume
  - type: volume
    source: datacache
    target: ${IBL_PATH_ROOT:?set IBL_PATH_ROOT path in .env file}/data

x-ibl-shared-mount: &ibl-shared-mount
  - type: bind
    source: ../../shared
    target: ${IBL_PATH_ROOT:?set IBL_PATH_ROOT path in .env file}/shared

x-shared-networks: &shared-networks
  networks:
    ibl-alyx:

<<: *shared-networks

volumes:
  datacache:
  pgdata:

services:
  # Postgres Server --------------------------------------------------------------------
  pgserv:
    image: postgres:13.3
    <<: *common-platform
    <<: *shared-networks
    user: postgres
    environment:
      - POSTGRES_USER=${ALYX_DB_USER:?set ALYX_DB_USER in .env file}
      - POSTGRES_PASSWORD=${ALYX_DB_PASSWORD:?set ALYX_DB_PASSWORD in .env file}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 20s
      start_period: 5s
      retries: 6
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Alyx Database ----------------------------------------------------------------------
  alyx:
    <<: *common-platform
    <<: *shared-networks
    volumes:
      - <<: *ibl-data-volume
      - <<: *ibl-shared-mount
    init: true
    depends_on:
      pgserv:
        condition: service_healthy
    build:
      context: ../..
      dockerfile: docker/ibl/alyx/Dockerfile
    environment:
      - IBL_PATH_ROOT=${IBL_PATH_ROOT:?set IBL_PATH_ROOT path in .env file}
      - PGUSER=${ALYX_DB_USER:?set ALYX_DB_USER in .env file}
      - PGPASSWORD=${ALYX_DB_PASSWORD:?set ALYX_DB_PASSWORD in .env file}
      - PGDBNAME=${ALYX_DB_NAME:-iblalyx}
      - PGHOST=${ALYX_DB_HOST:-pgserv}
      - HTTP_DATA_SERVER_LOGIN=${HTTP_DATA_SERVER_LOGIN:-}
      - HTTP_DATA_SERVER_PWD=${HTTP_DATA_SERVER_PWD:-}
      - ALYX_PORT=${ALYX_PORT:-8000}
      - ALYX_SECRET_KEY=${ALYX_SECRET_KEY:-0xdeadbeef}
    ports:
      - "${ALYX_PORT:-8000}:${ALYX_PORT:-8000}"
    working_dir: ${IBL_PATH_ROOT}
    command: [ "initdb", "dev" ]

  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=pgserv
      - ADMINER_DESIGN=nette
    ports:
      - 8081:8080
    <<: *shared-networks
