# cd IBL-pipeline/docker/ibl/alyx
# docker-compose up --build --detach pgserver alyx
# docker exec -dt alyx_db_server_0 alyx initdb dev

version: "2.4"

x-common-platform: &common-platform
  platform: linux/${LNX_ARCH:-x86_64}

x-ibl-data-volume: &ibl-data-volume
  - type: volume
    source: datacache
    target: ${IBL_PATH_ROOT:?set IBL_PATH_ROOT path in .env file}/data

x-ibl-shared-mount: &ibl-shared-mount
  - type: bind
    source: ../../../shared
    target: ${IBL_PATH_ROOT:?set IBL_PATH_ROOT path in .env file}/shared

x-shared-networks: &shared-networks
  networks:
    ibl_alyx:

<<: *shared-networks

volumes:
  datacache:
  pgdata:

services:
  # Postgres Server --------------------------------------------------------------------
  pgserver:
    container_name: postgres_db_server_0
    image: postgres:13-bullseye
    <<: *common-platform
    <<: *shared-networks
    environment:
      - POSTGRES_DB=${ALYX_DB_NAME:-alyxdb}
      - POSTGRES_USER=${ALYX_DB_USER:-alyxadmin}
      - POSTGRES_PASSWORD=${ALYX_DB_PASSWORD:?set ALYX_DB_PASSWORD in .env file}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 60s
      timeout: 120s
      start_period: 20s
      retries: 3
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5435:5432

  # Alyx Database ----------------------------------------------------------------------
  alyx:
    container_name: alyx_db_server_0
    <<: *common-platform
    <<: *shared-networks
    volumes:
      - <<: *ibl-data-volume
      - <<: *ibl-shared-mount
    init: true
    depends_on:
      pgserver:
        condition: service_healthy
    build:
      context: ../../..
      dockerfile: docker/ibl/alyx/Dockerfile
    environment:
      - IBL_PATH_ROOT=${IBL_PATH_ROOT:?set IBL_PATH_ROOT path in .env file}
      - HTTP_DATA_SERVER_LOGIN=${HTTP_DATA_SERVER_LOGIN:?set HTTP_DATA_SERVER_LOGIN in .env file}
      - HTTP_DATA_SERVER_PWD=${HTTP_DATA_SERVER_PWD:?set HTTP_DATA_SERVER_PWD in .env file}
      - PGPASSWORD=${ALYX_DB_PASSWORD:?set ALYX_DB_PASSWORD in .env file}
      - PGDATABASE=${ALYX_DB_NAME:-alyxdb}
      - PGUSER=${ALYX_DB_USER:-alyxadmin}
      - PGHOST=${PGHOST:-pgserver}
    ports:
      - "${ALYX_PORT:-8000}:${ALYX_PORT:-8000}"
    working_dir: ${IBL_PATH_ROOT}
    command: [ "loadpubdump", "startserver" ]
